adjective = raw_input('Type in an adjective: ')
second_adjective = raw_input('Another adjective: ')
third_adjective = raw_input('And another adjective: ')
fourth_adjective = raw_input('One more adjective: ')
plural_animal = raw_input('Plural animal (e.g., puppies): ')
verb = raw_input('Now a verb: ')
plural_noun = raw_input('Now a plural noun: ')
woman_musician = raw_input('The first name of a woman musician: ')
beverage = raw_input('A beverage: ')
plural_body_part = raw_input('And finally, a plural body part: ')

print('                                       ')
print("Excellent choice! Here's your story...")
print('----------------------------')
print('There once was a fearless programmer named ' + woman_musician + ' who wanted to build a ' + second_adjective + ' mobile app to help ' + third_adjective + ' ' + plural_animal + ' find new homes.')
print (woman_musician + ' stayed up all night, drinking lots of caffeinated ' + beverage + ' as she worked and worked trying to complete her ' + fourth_adjective + ' program.')
print ('Whenever ' + woman_musician + ' hit a dead end, she would exclaim *' + plural_noun + '*!')
print ('But she was not discouraged, and after a quick break to ' + verb + ' and clear her head, she got back to work.')
print ('By morning, when the sun started to rise, she let out a big yawn and stretched her ' + plural_body_part + '. Finally, she was done.')
